[package]
name = "diml"
version = "0.2.0"
authors = ["Dariusz Depta <depta@engos.de>"]
description = "Delimiter-Indented Markup Language (DIML) parser"
documentation = "https://docs.rs/diml"
repository = "https://github.com/EngosSoftware/diml.git"
keywords = ["delimiter", "indented", "markup", "language", "parser"]
categories = ["encoding"]
edition = "2024"
license = "MIT OR Apache-2.0"
include = [
    "docs/**",
    "src/**",
    "tests/**",
    "Cargo.lock",
    "Cargo.toml",
    "LICENSE*",
    "NOTICE",
    "/README.md"
]

[dependencies]
normalized-line-endings = "1.0.14"
